name: zap_baseline_scan
on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  zap_base_scan:
    name : web application base_scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          #target: 'http://192.168.49.2:30961' 
          #target: 'https://www.zaproxy.org/'
          target: 'http://www.itsecgames.com'
          cmd_options: '-a -d -T 5 -m 2'
          issue_title: OWASP Baseline Wordsmith
