name: zap_baseline_scan
on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  zap_base_scan:
    name : base_scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://192.168.49.2:30961' # target: 'https://localhost:8080'
