name: zap_baseline_scan
on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  zap_base_scan:
    name : base_scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://192.168.49.2:30961' # target: 'https://localhost:8080'
          cmd_options: '-a'
