#workflow_name: test-sonar-repo-scan.yml
name: sonar-repo-scan
on:
  workflow_dispatch:
  push:
jobs:
  sonar-repo-scan:
    uses: oykotbruce/wordsmith/.github/workflows/sonar-scanner.yaml@main
    with:
# Your Sonar Cloud Organization
# for example, ORG: ci-testing, bruce-ci-testing, bcgov-sonarcloud
#     ORG: <sonar_cloud_organization>
      ORG: bruce-ci-testing
# Your Project Key
# for example, PROJECT_KEY: bcgov-pipeline-templates, maven-test-bruce
      PROJECT_KEY: bruce-wh-li_github-slideshow
      URL: https://sonarcloud.io
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
